# on Cifar10

python main.py --default_root_dir="experiments/framestime_cifar10" --ckpt_path="experiments/framestime_cifar10/logger/resnet cifar10-dvs frames_time/version_2/checkpoints/model-epoch=012-val_acc=0.9345.ckpt" --num_workers=0 --gpus=1 --event_representation="frames_time" --timesteps=10 --dataset="cifar10-dvs" --batch_size=256 --max_epochs=60 --height=224 --width=224 --learning_rate=0.001 --log_every_n_steps=1 --mode="validate" --noise="background_activity" --severity=1

python main.py --default_root_dir="experiments/framestime_cifar10" --ckpt_path="experiments/framestime_cifar10/logger/resnet cifar10-dvs frames_time/version_2/checkpoints/model-epoch=012-val_acc=0.9345.ckpt" --num_workers=0 --gpus=1 --event_representation="frames_time" --timesteps=10 --dataset="cifar10-dvs" --batch_size=256 --max_epochs=60 --height=224 --width=224 --learning_rate=0.001 --log_every_n_steps=1 --mode="validate" --noise="background_activity" --severity=2

python main.py --default_root_dir="experiments/framestime_cifar10" --ckpt_path="experiments/framestime_cifar10/logger/resnet cifar10-dvs frames_time/version_2/checkpoints/model-epoch=012-val_acc=0.9345.ckpt" --num_workers=0 --gpus=1 --event_representation="frames_time" --timesteps=10 --dataset="cifar10-dvs" --batch_size=256 --max_epochs=60 --height=224 --width=224 --learning_rate=0.001 --log_every_n_steps=1 --mode="validate" --noise="background_activity" --severity=3

python main.py --default_root_dir="experiments/framestime_cifar10" --ckpt_path="experiments/framestime_cifar10/logger/resnet cifar10-dvs frames_time/version_2/checkpoints/model-epoch=012-val_acc=0.9345.ckpt" --num_workers=0 --gpus=1 --event_representation="frames_time" --timesteps=10 --dataset="cifar10-dvs" --batch_size=256 --max_epochs=60 --height=224 --width=224 --learning_rate=0.001 --log_every_n_steps=1 --mode="validate" --noise="background_activity" --severity=4

python main.py --default_root_dir="experiments/framestime_cifar10" --ckpt_path="experiments/framestime_cifar10/logger/resnet cifar10-dvs frames_time/version_2/checkpoints/model-epoch=012-val_acc=0.9345.ckpt" --num_workers=0 --gpus=1 --event_representation="frames_time" --timesteps=10 --dataset="cifar10-dvs" --batch_size=256 --max_epochs=60 --height=224 --width=224 --learning_rate=0.001 --log_every_n_steps=1 --mode="validate" --noise="background_activity" --severity=5